In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [32]:
dataFolder = ''
dataFile = dataFolder + "iris.csv"
print(dataFile)

iris.csv


In [33]:
df = pd.read_csv(dataFile)
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [34]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [35]:
print(X[0:5])
print(y[0:5])

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [36]:
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [37]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [38]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [39]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [41]:
print(X_train[0:5])

[[5.2 3.4 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.5 0.3]]


In [42]:
print(y_train[0:5])

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [43]:
print(X_test[0:5])

[[6.1 2.6 5.6 1.4]
 [6.5 3.2 5.1 2. ]
 [5.  2.  3.5 1. ]
 [5.5 2.4 3.7 1. ]
 [4.4 2.9 1.4 0.2]]


In [44]:
print(y_test[0:5])

[[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [45]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dense(3, activation='sigmoid')
  ])
model

In [46]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [51]:
model.fit(X_train, y_train, batch_size=10, epochs=100)


Epoch 1/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5520 - accuracy: 0.7563
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5440 - accuracy: 0.7311
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 0.5365 - accuracy: 0.8067
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5299 - accuracy: 0.8403
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5230 - accuracy: 0.8319
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5170 - accuracy: 0.8487
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5112 - accuracy: 0.8571
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 0.5050 - accuracy: 0.8571
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4994 - accuracy: 0.8739
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4940 - accuracy: 0.8487
Epoch 11/

12/12 [==============================] - 0s 2ms/step - loss: 0.1898 - accuracy: 0.9748
Epoch 84/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1876 - accuracy: 0.9748
Epoch 85/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1861 - accuracy: 0.9664
Epoch 86/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1829 - accuracy: 0.9748
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 0.1809 - accuracy: 0.9748
Epoch 88/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1781 - accuracy: 0.9748
Epoch 89/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1775 - accuracy: 0.9748
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1746 - accuracy: 0.9832
Epoch 91/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1728 - accuracy: 0.9664
Epoch 92/100
12/12 [==============================] - 0s 2ms/step - loss: 0.1718 - accuracy: 0.9748
Epoch 93/100


In [52]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.12890873849391937
Test accuracy: 1.0


In [53]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 11ms/step


array([[0.00358062, 0.60638815, 0.8832333 ],
       [0.00731886, 0.65237707, 0.76782316],
       [0.09081833, 0.7650291 , 0.194074  ],
       [0.18692528, 0.77980965, 0.10099113],
       [0.9702359 , 0.5686012 , 0.00419085],
       [0.00180551, 0.5597446 , 0.94068897],
       [0.00485369, 0.62759817, 0.836653  ],
       [0.09040471, 0.7648241 , 0.19185771],
       [0.00411208, 0.6162367 , 0.8658921 ],
       [0.07236703, 0.7579321 , 0.22739218],
       [0.97204524, 0.5631428 , 0.00403869],
       [0.97086906, 0.56680423, 0.00413473],
       [0.03601108, 0.7333048 , 0.3835662 ],
       [0.97048444, 0.5681639 , 0.00416277],
       [0.9720306 , 0.56295955, 0.00404536],
       [0.00976587, 0.6698197 , 0.71330374],
       [0.00325639, 0.60080475, 0.8905127 ],
       [0.1330265 , 0.7766496 , 0.1350914 ],
       [0.97461146, 0.5542622 , 0.00382664],
       [0.97556883, 0.55070233, 0.0037473 ],
       [0.96165234, 0.59125996, 0.00484186],
       [0.9729495 , 0.56018156, 0.00396438],
       [0.

In [54]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
Predicted: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
